package com.aprohirdetes.server;

import java.util.ArrayList;

import org.mongodb.morphia.Datastore;
import org.mongodb.morphia.Key;
import com.aprohirdetes.model.HelysegCache;
import com.aprohirdetes.model.Hirdetes;
import com.aprohirdetes.model.HirdetesTipus;
import com.aprohirdetes.model.Hirdeto;
import com.aprohirdetes.model.KategoriaCache;
import com.aprohirdetes.utils.MongoUtils;

public class AproData {

	private static final int max1 = 65;
	private static final int max2 = 89;
	private static final int max3 = 91;
	private static final int max4 = 107;

	private static ArrayList<String> array1 = new ArrayList<String>();
	private static ArrayList<String> array2 = new ArrayList<String>();
	private static ArrayList<String> array3 = new ArrayList<String>();
	private static ArrayList<String> array4 = new ArrayList<String>();

	private static void setRandomData() {
		array1.add("Erőforrás-alapú megközelítéssel kell");
		array1.add("Egy absztrakciós létra mentén kell");
		array1.add("Alapvető fontosságú");
		array1.add("Kiemelt projektünk");
		array1.add("A menedzsment célja");
		array1.add("Teljes összhangban kell");
		array1.add("Belső kommunikáció révén kell");
		array1.add("Csapatmunkában szükséges");
		array1.add("Még ma szükséges");
		array1.add("Nem tűr halasztást");
		array1.add("Fontos lenne");
		array1.add("Szükséges lenne");
		array1.add("Szükséges");
		array1.add("Vállalatunk célja");
		array1.add("Kiemelt fontosságú feladat");
		array1.add("Ennek szellemében kell");
		array1.add("Formállogikai alapon kellene");
		array1.add("Alkotó folyamat keretében kell");
		array1.add("Felelősséggel kell");
		array1.add("A következőt kell tennünk:");
		array1.add("Egyetlen megoldásunk van:");
		array1.add("Az egyetlen kiút:");
		array1.add("Tanácsadóink szerint célunk:");
		array1.add("A menedzsment szeretné");
		array1.add("Az üzletág szeretné");
		array1.add("Most kell");
		array1.add("Nincs más hátra mint");
		array1.add("Ne felejtsük el");
		array1.add("Ne szalasszuk el");
		array1.add("Szeretném");
		array1.add("Célom");
		array1.add("Az eddigiek szerint kell");
		array1.add("A lényeg:");
		array1.add("Feladatunk:");
		array1.add("Küldetésünk:");
		array1.add("A mai legfontosabb prioritás:");
		array1.add("Megpróbáljuk");
		array1.add("Megpróbálom");
		array1.add("Megkíséreljük");
		array1.add("Megkísérlem");
		array1.add("Próbáljátok meg");
		array1.add("Meg kell próbálnunk");
		array1.add("Küldetésem");
		array1.add("Új koncepció szerint kell");
		array1.add("Azonnal szükséges");
		array1.add("Egy megoldás van:");
		array1.add("Kreatív módon kell");
		array1.add("Sürgősen szükséges");
		array1.add("Személyes célom");
		array1.add("Nincs más dolgunk mint");
		array1.add("Nincs más feladatom mint");
		array1.add("Legfontosabb feladatom");
		array1.add("Legfontosabb küldetésem");
		array1.add("Elsődleges fontosságú lenne");
		array1.add("Elengedhetetlen lenne");
		array1.add("Létfontosságú dolog");
		array1.add("Elengedhetetlenül fontos lenne");
		array1.add("Itt az idő");
		array1.add("Nem halaszthatjuk el");
		array1.add("Kreatív módon kell");
		array1.add("Elemzések segítségével kell");
		array1.add("Kreatív módon kéne");
		array1.add("Látványosan kell");
		array1.add("Minél feltűnőbben kell");
		array1.add("Professzionális módon kell");
		array1.add("Megfelelő időzítéssel kell");

		array2.add("implementálni");
		array2.add("átültetni");
		array2.add("aggregálni");
		array2.add("aktívan menedzselni");
		array2.add("aktiválni");
		array2.add("allokálni");
		array2.add("analizálni");
		array2.add("áramvonalasítani");
		array2.add("arányosítani");
		array2.add("áthangszerelni");
		array2.add("átváltoztatni");
		array2.add("átvariálni");
		array2.add("átvezetni");
		array2.add("bátorítani");
		array2.add("betanítani");
		array2.add("befolyásolni");
		array2.add("benchmarkolni");
		array2.add("bevetni");
		array2.add("birtokba venni");
		array2.add("bővíteni");
		array2.add("szűkíteni");
		array2.add("ellenőrizni");
		array2.add("előmozdítani");
		array2.add("életre kelteni");
		array2.add("facilitálni");
		array2.add("fejleszteni");
		array2.add("felnevelni");
		array2.add("felruházni");
		array2.add("felszabadítani");
		array2.add("forradalmasítani");
		array2.add("generálni");
		array2.add("hasznosítani");
		array2.add("hatékonyabbá tenni");
		array2.add("innovatívan fejleszteni");
		array2.add("integrálni");
		array2.add("iterálni");
		array2.add("kihangsúlyozni");
		array2.add("kiválasztani");
		array2.add("leválogatni");
		array2.add("leválasztani");
		array2.add("kihasználni");
		array2.add("kiterjeszteni");
		array2.add("kultiválni");
		array2.add("lefoglalni");
		array2.add("lehetővé tenni");
		array2.add("márkázni");
		array2.add("maximalizálni");
		array2.add("meghatározni");
		array2.add("megragadni");
		array2.add("megváltoztatni");
		array2.add("menedzselni");
		array2.add("monetizálni");
		array2.add("motiválni");
		array2.add("növelni");
		array2.add("nyilvánvalóvá tenni");
		array2.add("optimalizálni");
		array2.add("ösztönözni");
		array2.add("kiépíteni");
		array2.add("rávilágítani");
		array2.add("racionálisan végiggondolni");
		array2.add("racionalizálni");
		array2.add("ritkítani");
		array2.add("sűríteni");
		array2.add("strategizálni");
		array2.add("struktúrálni");
		array2.add("szakmailag felügyelni");
		array2.add("szétszabdalni");
		array2.add("szimulálni");
		array2.add("szindikálni");
		array2.add("szinergizálni");
		array2.add("szinkronba hozni");
		array2.add("sztenderdizálni");
		array2.add("szintetizálni");
		array2.add("támogatni");
		array2.add("targetálni");
		array2.add("termékesíteni");
		array2.add("testreszabni");
		array2.add("toborozni");
		array2.add("tipizálni");
		array2.add("tiszta lappal kezdeni");
		array2.add("transzformálni");
		array2.add("túlteljesíteni");
		array2.add("új kontextusba helyezni");
		array2.add("újra feltalálni");
		array2.add("újra meghatározni");
		array2.add("újradefiniálni");
		array2.add("újrapozícionálni");
		array2.add("újratermelni");
		array2.add("vizionálni");
		array2.add("vizualizálni");

		array3.add("a közösségi normáknak megfelelő");
		array3.add("a decentralizált");
		array3.add("a dinamikusan növekvő");
		array3.add("a dinamikusan növekvő");
		array3.add("a divergens");
		array3.add("a fontos");
		array3.add("a felvállalható");
		array3.add("a forradalmian új");
		array3.add("a funkció-specifikus");
		array3.add("a globális preferenciák szerinti");
		array3.add("a hatásos");
		array3.add("a hatékony");
		array3.add("a hibátlan");
		array3.add("a holisztikus");
		array3.add("a kihívást jelentő");
		array3.add("a konvergens");
		array3.add("a konzisztens");
		array3.add("a korrigálható");
		array3.add("a korreláló");
		array3.add("a költséghatékony");
		array3.add("a közszolgáltatási");
		array3.add("a kultúraidegen");
		array3.add("a kritikus");
		array3.add("a kvázi-projekt-szerű");
		array3.add("a marketing-szemléletű");
		array3.add("a megfelelően előkészített");
		array3.add("a meghatározandó");
		array3.add("a megtérülő");
		array3.add("a metakommunkiációs");
		array3.add("a one-stop-shop-szerű");
		array3.add("az összehangolt");
		array3.add("a piacvezető");
		array3.add("a proaktív");
		array3.add("a prudens");
		array3.add("a reakcióképes");
		array3.add("a robosztus");
		array3.add("a racionális");
		array3.add("a rendszeres");
		array3.add("a rugalmas");
		array3.add("a sajátos");
		array3.add("a stagnáló");
		array3.add("a stratégiai céloknak megfelelő");
		array3.add("a stratégiáknak megfelelő");
		array3.add("a súrlódásmentes");
		array3.add("a szárnyaló");
		array3.add("a széles körben használt");
		array3.add("a személyre szabott");
		array3.add("a szinergizált");
		array3.add("a tudatos");
		array3.add("a vállalati szintű");
		array3.add("a vállalati szintű");
		array3.add("a vállalatspecifikus");
		array3.add("a vállalható");
		array3.add("a valós idejű");
		array3.add("a vertikális");
		array3.add("a világszínvonalú");
		array3.add("a virtuális");
		array3.add("a vizionált");
		array3.add("a vonzáskörzeten belüli");
		array3.add("a XXI. századi színvonalú");
		array3.add("az autonóm");
		array3.add("a heteronóm");
		array3.add("az apatikus");
		array3.add("a közömbös");
		array3.add("a személyközi");
		array3.add("a szűkös");
		array3.add("a rutinos");
		array3.add("az atipikus");
		array3.add("az átlátható");
		array3.add("az attraktív");
		array3.add("az egységsugarú");
		array3.add("az együttműködő");
		array3.add("az elosztott");
		array3.add("az elővárosi");
		array3.add("az előnyös");
		array3.add("az értéklánc menti");
		array3.add("az értéknövelt");
		array3.add("az európai színvonalú");
		array3.add("az európai uniós");
		array3.add("az extenzív");
		array3.add("az időzített");
		array3.add("az igazgató úr által is említett");
		array3.add("az innovatív");
		array3.add("az integrált");
		array3.add("az interaktív");
		array3.add("az intuitív");
		array3.add("az irányvonalnak megfelelő");
		array3.add("az ügyfélbarát");
		array3.add("az ügyfélközpontú");
		array3.add("az ügyféloldali");
		array3.add("az ütemes");
		array3.add("a távolsági");

		array4.add("szinergiákat");
		array4.add("adatbázist");
		array4.add("ágazatközi munkamegosztást");
		array4.add("akció-rádiuszt");
		array4.add("akcióterveket");
		array4.add("belső hatékonyságot");
		array4.add("beruházási megtérülést");
		array4.add("beszállító-menedzsmentet");
		array4.add("csatlakozási pontokat");
		array4.add("csapatot");
		array4.add("csatornákat");
		array4.add("derogációt");
		array4.add("desztinációszenzitív portfoliót");
		array4.add("együttműködéseket");
		array4.add("egységköltséget");
		array4.add("egység-díjtételt");
		array4.add("ellátási láncokat");
		array4.add("emberi erőforrást");
		array4.add("eredményjavító hatást");
		array4.add("erőforrás-menedzsmentet");
		array4.add("erőforrásokat");
		array4.add("értékláncot");
		array4.add("értékesítési rendszert");
		array4.add("fejlesztéseket");
		array4.add("feladatmegosztást");
		array4.add("flotta-menedzsmentet");
		array4.add("fogyasztói bázist");
		array4.add("frontvonalat");
		array4.add("front-office-t");
		array4.add("front-office on-stage vonalat");
		array4.add("front-office backstage vonalat");
		array4.add("hálózatokat");
		array4.add("háttérszolgáltatásokat");
		array4.add("hatalmi centrumot");
		array4.add("imázs-alakítást");
		array4.add("infrastruktúrákat");
		array4.add("intermodalitást");
		array4.add("interoperabilitást");
		array4.add("irányelveket");
		array4.add("irányítási filozófiát");
		array4.add("jogharmonizációt");
		array4.add("kapacitás-kihasználtságot");
		array4.add("kapcsolatokat");
		array4.add("kezdeményezéseket");
		array4.add("koncepciót");
		array4.add("kontextust");
		array4.add("kontrollingot");
		array4.add("konvergenciákat");
		array4.add("költségérzékeny szegmenst");
		array4.add("környezet-elemzést");
		array4.add("kritériumokat");
		array4.add("látványtechnológiát");
		array4.add("leválasztási stratégiát");
		array4.add("marketing-kutatást");
		array4.add("marketing-miómát");
		array4.add("marketing-szemléletet");
		array4.add("megoldásokat");
		array4.add("méretgazdaságosságot");
		array4.add("mérföldköveket");
		array4.add("metodológiákat");
		array4.add("minőségi szolgáltatásokat");
		array4.add("minpőségi indikátorokat");
		array4.add("minőség-monitoringot");
		array4.add("munkacsoportot");
		array4.add("működési költségeket");
		array4.add("optimalizálási koncepciót");
		array4.add("outsourcingot");
		array4.add("paradigmákat");
		array4.add("piaci megjelenést");
		array4.add("piaci potenciált");
		array4.add("piaci pozíciót");
		array4.add("piaci réseket");
		array4.add("piaci trendeket");
		array4.add("piacokat");
		array4.add("pilot projektet");
		array4.add("platformokat");
		array4.add("portálokat");
		array4.add("projekteket");
		array4.add("reklámanyagot");
		array4.add("rendszereket");
		array4.add("rendszertervezési technológiát");
		array4.add("sémákat");
		array4.add("stratégiai célokat");
		array4.add("szabályozásokat");
		array4.add("szegmentumokat");
		array4.add("személyszállítást");
		array4.add("szervezeti kultúrát");
		array4.add("szolgáltatási folyamatrendszert");
		array4.add("szolgáltatás-felügyeletet");
		array4.add("szolgáltatást");
		array4.add("sztenderdizációt");
		array4.add("támogató tevékenységet");
		array4.add("termékpalettát");
		array4.add("termékportfolió-átalakítást");
		array4.add("technológiákat");
		array4.add("tevékenység-menedzsmentet");
		array4.add("tudásközpontot");
		array4.add("tranzakciós költséget");
		array4.add("újraelosztó-rendszert");
		array4.add("ügyfeleket");
		array4.add("ügyfélreferenst");
		array4.add("ügyfél-kiszolgálást");
		array4.add("ügyfélorientált trendeket");
		array4.add("üzletmenetet");
		array4.add("vállalati imázst");
		array4.add("VIP-ügyfeleket");
		array4.add("versenyhelyzetet");
		array4.add("versenyelőny-forrást");
	}

	private static String getRandomCim() {
		int index1 = (int) Math.round(Math.random() * max1);
		int index2 = (int) Math.round(Math.random() * max2);
		int index3 = (int) Math.round(Math.random() * max3);
		int index4 = (int) Math.round(Math.random() * max4);

		return array1.get(index1) + " " + array2.get(index2) + " "
				+ array3.get(index3) + " " + array4.get(index4) + ".";
	}

	public static void main(String[] args) {
		AproConfig.APP_CONFIG.put("DB.MONGO.DB", "aprocom");
		
		KategoriaCache.loadCache();
		HelysegCache.loadCache();
		setRandomData();
		
		Datastore datastore = MongoUtils.getDatastore();

		for(int i=0; i<10000; i++) {
			Hirdetes hi = new Hirdetes();
			hi.setTipus(HirdetesTipus.KINAL);
			hi.setCim(getRandomCim());
			hi.setKategoriaId(KategoriaCache.getRandomKategoria().getId());
			hi.setHelysegId(HelysegCache.getRandomHelyseg().getId());
			hi.setSzoveg(getRandomCim() + ", mivel " + getRandomCim() + " Mindezt azért, mert " + getRandomCim());
			//hi.setEgyebInfo();
			try {
				hi.setAr((int)Math.round(Math.random() * 100000));
			} catch (NumberFormatException nfe) {
				hi.setAr(0);
			}
			
			hi.tokenize();
	
			Hirdeto ho = new Hirdeto();
			ho.setNev("Vámos Balázs");
			ho.setEmail("bvamos@zuriel.net");
			ho.setTelefon("+36-30-6388093");
			ho.setOrszag("Magyarország");
			ho.setIranyitoSzam("9700");
			ho.setTelepules("Szombathely");
			ho.setCim("Kassak L. 11.");
	
			hi.setHirdeto(ho);
	
			Key<Hirdetes> id = datastore.save(hi);
			System.out.println(id);
		}
	}

}
